"""Add asset phase 2 mapping models

Revision ID: c98c94adc301
Revises: 0008_assets
Create Date: 2026-09-13 10:44:08.447901
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c98c94adc301'
down_revision: Union[str, Sequence[str], None] = '0008_assets'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_repairs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('previous_store_id', sa.Integer(), nullable=True),
    sa.Column('previous_office_id', sa.Integer(), nullable=True),
    sa.Column('previous_section_id', sa.Integer(), nullable=True),
    sa.Column('previous_status', sa.String(length=30), nullable=False),
    sa.Column('sent_date', sa.Date(), nullable=False),
    sa.Column('sent_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('returned_by', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_repairs_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_office_id'], ['offices.id'], name=op.f('fk_asset_repairs_previous_office_id_offices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_section_id'], ['sections.id'], name=op.f('fk_asset_repairs_previous_section_id_sections'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_store_id'], ['stores.id'], name=op.f('fk_asset_repairs_previous_store_id_stores'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['returned_by'], ['users.id'], name=op.f('fk_asset_repairs_returned_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], name=op.f('fk_asset_repairs_sent_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_repairs'))
    )
    op.create_table('issue_line_assets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('issue_line_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_issue_line_assets_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issue_line_id'], ['issue_lines.id'], name=op.f('fk_issue_line_assets_issue_line_id_issue_lines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_line_assets'))
    )
    op.create_index('ix_issue_line_assets_asset_id', 'issue_line_assets', ['asset_id'], unique=False)
    op.create_table('transfer_line_assets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('transfer_line_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_transfer_line_assets_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_line_id'], ['stock_transfer_lines.id'], name=op.f('fk_transfer_line_assets_transfer_line_id_stock_transfer_lines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_line_assets'))
    )
    op.create_index('ix_transfer_line_assets_asset_id', 'transfer_line_assets', ['asset_id'], unique=False)
    op.create_table('stock_return_line_assets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stock_return_line_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_stock_return_line_assets_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_return_line_id'], ['stock_return_lines.id'], name=op.f('fk_stock_return_line_assets_stock_return_line_id_stock_return_lines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_return_line_assets'))
    )
    op.create_index('ix_stock_return_line_assets_asset_id', 'stock_return_line_assets', ['asset_id'], unique=False)
    op.alter_column('adjustment_lines', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('adjustment_lines', 'unit_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_adjustment_lines_item'), table_name='adjustment_lines')
    op.alter_column('adjustments', 'financial_year_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('adjustments', 'store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('adjustments', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('adjustments', 'authorized_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('adjustments', 'posted_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_adjustments_store_status'), table_name='adjustments')
    op.drop_index(op.f('ix_adjustments_verification'), table_name='adjustments')
    op.drop_constraint(op.f('uq_adjustments_verification_type'), 'adjustments', type_='unique')
    op.create_unique_constraint('uq_adjustments_verification', 'adjustments', ['verification_id'])
    op.alter_column('asset_movements', 'from_store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('asset_movements', 'to_store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('asset_movements', 'from_office_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('asset_movements', 'from_section_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('asset_movements', 'to_office_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('asset_movements', 'to_section_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('asset_movements', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('assets', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('assets', 'current_store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('assets', 'current_office_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('assets', 'current_section_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('assets', 'acquisition_financial_year_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('assets', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('assets', 'updated_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('uq_assets_serial_no_nonnull'), table_name='assets', postgresql_where='(serial_no IS NOT NULL)')
    op.alter_column('categories', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('categories', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('central_store_requisition_lines', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_csr_lines_item'), table_name='central_store_requisition_lines')
    op.alter_column('central_store_requisitions', 'financial_year_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('central_store_requisitions', 'requesting_office_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('central_store_requisitions', 'requesting_store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('central_store_requisitions', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('central_store_requisitions', 'branch_approved_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('central_store_requisitions', 'central_approved_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('central_store_requisitions', 'closed_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_csr_fy_date'), table_name='central_store_requisitions')
    op.drop_index(op.f('ix_csr_requesting_store_status'), table_name='central_store_requisitions')
    op.alter_column('financial_years', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('uq_current_financial_year'), table_name='financial_years', postgresql_where='(is_current = true)')
    op.alter_column('indent_lines', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('indent_lines', 'remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_indent_lines_item'), table_name='indent_lines')
    op.alter_column('indents', 'financial_year_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('indents', 'store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('indents', 'office_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('indents', 'section_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('indents', 'remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('indents', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_indents_fy_date'), table_name='indents')
    op.drop_index(op.f('ix_indents_store_status'), table_name='indents')
    op.alter_column('inventory_policies', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('inventory_policies', 'store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('inventory_policies', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('inventory_policies', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('inventory_policies', 'updated_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_inventory_policies_updated_by_users'), 'inventory_policies', type_='foreignkey')
    op.drop_constraint(op.f('fk_inventory_policies_created_by_users'), 'inventory_policies', type_='foreignkey')
    op.create_foreign_key(op.f('fk_inventory_policies_updated_by_users'), 'inventory_policies', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_inventory_policies_created_by_users'), 'inventory_policies', 'users', ['created_by'], ['id'])
    op.alter_column('issue_lines', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('issue_lines', 'unit_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('issue_lines', 'remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_issue_lines_item'), table_name='issue_lines')
    op.alter_column('issues', 'financial_year_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('issues', 'source_store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('issues', 'destination_office_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('issues', 'destination_section_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('issues', 'remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('issues', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('issues', 'posted_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_issues_destination'), table_name='issues')
    op.drop_index(op.f('ix_issues_store_date'), table_name='issues')
    op.alter_column('items', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('items', 'category_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('items', 'unit_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('items', 'specification',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('items', 'remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_items_category_id'), table_name='items')
    op.drop_index(op.f('ix_items_unit_id'), table_name='items')
    op.create_unique_constraint('uq_items_name_category', 'items', ['name', 'category_id'])
    op.alter_column('offices', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('offices', 'parent_office_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('offices', 'remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('opening_stock_lines', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('opening_stock_lines', 'unit_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('opening_stock_lines', 'remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('opening_stocks', 'financial_year_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('opening_stocks', 'store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('opening_stocks', 'remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('opening_stocks', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('opening_stocks', 'verified_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('opening_stocks', 'posted_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_opening_stocks_store_fy_status'), table_name='opening_stocks')
    op.alter_column('permissions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('permissions', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('petty_purchase_lines', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('petty_purchase_lines', 'unit_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_petty_purchase_lines_item'), table_name='petty_purchase_lines')
    op.alter_column('petty_purchases', 'financial_year_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('petty_purchases', 'store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('petty_purchases', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('petty_purchases', 'verified_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('petty_purchases', 'posted_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_petty_purchases_fy_date'), table_name='petty_purchases')
    op.drop_index(op.f('ix_petty_purchases_indent'), table_name='petty_purchases')
    op.drop_index(op.f('ix_petty_purchases_store_status'), table_name='petty_purchases')
    op.drop_constraint(op.f('uq_receipt_line_assets_line_asset'), 'receipt_line_assets', type_='unique')
    op.alter_column('receipt_lines', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('receipt_lines', 'unit_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_receipt_lines_item'), table_name='receipt_lines')
    op.alter_column('receipts', 'financial_year_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('receipts', 'store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('receipts', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('receipts', 'verified_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('receipts', 'posted_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_receipts_fy_date'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_store_status'), table_name='receipts')
    op.alter_column('role_permissions', 'role_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('role_permissions', 'permission_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('roles', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('roles', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('sections', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sections', 'office_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('sections', 'remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_sections_office_id'), table_name='sections')
    op.alter_column('stock_accounts', 'store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_accounts', 'financial_year_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_accounts', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_batches', 'store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_batches', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_batches', 'financial_year_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_stock_batches_item_expiry'), table_name='stock_batches')
    op.alter_column('stock_movements', 'financial_year_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_movements', 'store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_movements', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_movements', 'remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('stock_movements', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_stock_movements_posting_group'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_reference'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_store_fy_item_date'), table_name='stock_movements')
    op.alter_column('stock_return_lines', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_return_lines', 'unit_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_stock_return_lines_issue_line'), table_name='stock_return_lines')
    op.drop_index(op.f('ix_stock_return_lines_item'), table_name='stock_return_lines')
    op.alter_column('stock_returns', 'financial_year_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_returns', 'store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_returns', 'returning_office_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('stock_returns', 'returning_section_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('stock_returns', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('stock_returns', 'verified_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('stock_returns', 'posted_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_stock_returns_fy_date'), table_name='stock_returns')
    op.drop_index(op.f('ix_stock_returns_issue'), table_name='stock_returns')
    op.drop_index(op.f('ix_stock_returns_store_status'), table_name='stock_returns')
    op.alter_column('stock_transfer_lines', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_transfer_lines', 'unit_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_transfer_lines_item'), table_name='stock_transfer_lines')
    op.alter_column('stock_transfers', 'financial_year_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_transfers', 'source_store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_transfers', 'destination_store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_transfers', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_transfers', 'dispatched_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('stock_transfers', 'received_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('stock_transfers', 'closed_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_transfers_destination_status'), table_name='stock_transfers')
    op.drop_index(op.f('ix_transfers_requisition'), table_name='stock_transfers')
    op.drop_index(op.f('ix_transfers_source_status'), table_name='stock_transfers')
    op.alter_column('stock_verification_lines', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_stock_verification_lines_item'), table_name='stock_verification_lines')
    op.alter_column('stock_verifications', 'financial_year_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_verifications', 'store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_verifications', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_verifications', 'counted_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('stock_verifications', 'authorized_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('stock_verifications', 'closed_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_stock_verifications_fy_date'), table_name='stock_verifications')
    op.drop_index(op.f('ix_stock_verifications_store_status'), table_name='stock_verifications')
    op.alter_column('stores', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('stores', 'office_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stores', 'remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_stores_office_id'), table_name='stores')
    op.alter_column('transfer_discrepancies', 'reported_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('transfer_discrepancies', 'resolved_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_transfer_discrepancies_transfer_status'), table_name='transfer_discrepancies')
    op.alter_column('units', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('unserviceable_lines', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('unserviceable_lines', 'unit_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_unserviceable_lines_item'), table_name='unserviceable_lines')
    op.alter_column('unserviceable_materials', 'financial_year_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('unserviceable_materials', 'store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('unserviceable_materials', 'reported_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('unserviceable_materials', 'verified_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('unserviceable_materials', 'authorized_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('unserviceable_materials', 'posted_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_unserviceable_fy_date'), table_name='unserviceable_materials')
    op.drop_index(op.f('ix_unserviceable_store_status'), table_name='unserviceable_materials')
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('user_stores', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('user_stores', 'store_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'office_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('users', 'section_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('users', 'remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_office_id'), table_name='users')
    op.drop_index(op.f('ix_users_section_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_section_id'), 'users', ['section_id'], unique=False)
    op.create_index(op.f('ix_users_office_id'), 'users', ['office_id'], unique=False)
    op.alter_column('users', 'remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'section_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('users', 'office_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_stores', 'store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('user_stores', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('ix_unserviceable_store_status'), 'unserviceable_materials', ['store_id', 'status'], unique=False)
    op.create_index(op.f('ix_unserviceable_fy_date'), 'unserviceable_materials', ['financial_year_id', 'date'], unique=False)
    op.alter_column('unserviceable_materials', 'posted_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('unserviceable_materials', 'authorized_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('unserviceable_materials', 'verified_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('unserviceable_materials', 'reported_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('unserviceable_materials', 'store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('unserviceable_materials', 'financial_year_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('ix_unserviceable_lines_item'), 'unserviceable_lines', ['item_id'], unique=False)
    op.alter_column('unserviceable_lines', 'unit_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('unserviceable_lines', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('units', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_transfer_discrepancies_transfer_status'), 'transfer_discrepancies', ['transfer_id', 'status'], unique=False)
    op.alter_column('transfer_discrepancies', 'resolved_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('transfer_discrepancies', 'reported_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('ix_stores_office_id'), 'stores', ['office_id'], unique=False)
    op.alter_column('stores', 'remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('stores', 'office_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('stores', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_stock_verifications_store_status'), 'stock_verifications', ['store_id', 'status'], unique=False)
    op.create_index(op.f('ix_stock_verifications_fy_date'), 'stock_verifications', ['financial_year_id', 'verification_date'], unique=False)
    op.alter_column('stock_verifications', 'closed_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('stock_verifications', 'authorized_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('stock_verifications', 'counted_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('stock_verifications', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('stock_verifications', 'store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('stock_verifications', 'financial_year_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('ix_stock_verification_lines_item'), 'stock_verification_lines', ['item_id'], unique=False)
    op.alter_column('stock_verification_lines', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('ix_transfers_source_status'), 'stock_transfers', ['source_store_id', 'status'], unique=False)
    op.create_index(op.f('ix_transfers_requisition'), 'stock_transfers', ['requisition_id'], unique=False)
    op.create_index(op.f('ix_transfers_destination_status'), 'stock_transfers', ['destination_store_id', 'status'], unique=False)
    op.alter_column('stock_transfers', 'closed_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('stock_transfers', 'received_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('stock_transfers', 'dispatched_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('stock_transfers', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('stock_transfers', 'destination_store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('stock_transfers', 'source_store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('stock_transfers', 'financial_year_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('ix_transfer_lines_item'), 'stock_transfer_lines', ['item_id'], unique=False)
    op.alter_column('stock_transfer_lines', 'unit_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('stock_transfer_lines', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('ix_stock_returns_store_status'), 'stock_returns', ['store_id', 'status'], unique=False)
    op.create_index(op.f('ix_stock_returns_issue'), 'stock_returns', ['original_issue_id'], unique=False)
    op.create_index(op.f('ix_stock_returns_fy_date'), 'stock_returns', ['financial_year_id', 'return_date'], unique=False)
    op.alter_column('stock_returns', 'posted_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('stock_returns', 'verified_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('stock_returns', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('stock_returns', 'returning_section_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('stock_returns', 'returning_office_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('stock_returns', 'store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('stock_returns', 'financial_year_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('ix_stock_return_lines_item'), 'stock_return_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_return_lines_issue_line'), 'stock_return_lines', ['original_issue_line_id'], unique=False)
    op.alter_column('stock_return_lines', 'unit_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('stock_return_lines', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('ix_stock_movements_store_fy_item_date'), 'stock_movements', ['store_id', 'financial_year_id', 'item_id', 'movement_date'], unique=False)
    op.create_index(op.f('ix_stock_movements_reference'), 'stock_movements', ['reference_type', 'reference_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_posting_group'), 'stock_movements', ['posting_group_id'], unique=False)
    op.alter_column('stock_movements', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('stock_movements', 'remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('stock_movements', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('stock_movements', 'store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('stock_movements', 'financial_year_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('ix_stock_batches_item_expiry'), 'stock_batches', ['item_id', 'expiry_date'], unique=False)
    op.alter_column('stock_batches', 'financial_year_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('stock_batches', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('stock_batches', 'store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('stock_accounts', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('stock_accounts', 'financial_year_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('stock_accounts', 'store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('ix_sections_office_id'), 'sections', ['office_id'], unique=False)
    op.alter_column('sections', 'remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sections', 'office_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('sections', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('roles', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('roles', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('role_permissions', 'permission_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('role_permissions', 'role_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('ix_receipts_store_status'), 'receipts', ['store_id', 'status'], unique=False)
    op.create_index(op.f('ix_receipts_fy_date'), 'receipts', ['financial_year_id', 'receipt_date'], unique=False)
    op.alter_column('receipts', 'posted_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('receipts', 'verified_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('receipts', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('receipts', 'store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('receipts', 'financial_year_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('ix_receipt_lines_item'), 'receipt_lines', ['item_id'], unique=False)
    op.alter_column('receipt_lines', 'unit_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('receipt_lines', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_receipt_line_assets_line_asset'), 'receipt_line_assets', ['receipt_line_id', 'asset_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_petty_purchases_store_status'), 'petty_purchases', ['store_id', 'status'], unique=False)
    op.create_index(op.f('ix_petty_purchases_indent'), 'petty_purchases', ['indent_id'], unique=False)
    op.create_index(op.f('ix_petty_purchases_fy_date'), 'petty_purchases', ['financial_year_id', 'purchase_date'], unique=False)
    op.alter_column('petty_purchases', 'posted_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('petty_purchases', 'verified_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('petty_purchases', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('petty_purchases', 'store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('petty_purchases', 'financial_year_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('ix_petty_purchase_lines_item'), 'petty_purchase_lines', ['item_id'], unique=False)
    op.alter_column('petty_purchase_lines', 'unit_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('petty_purchase_lines', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('permissions', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('permissions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_opening_stocks_store_fy_status'), 'opening_stocks', ['store_id', 'financial_year_id', 'status'], unique=False)
    op.alter_column('opening_stocks', 'posted_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('opening_stocks', 'verified_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('opening_stocks', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('opening_stocks', 'remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('opening_stocks', 'store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('opening_stocks', 'financial_year_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('opening_stock_lines', 'remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('opening_stock_lines', 'unit_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('opening_stock_lines', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('offices', 'remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('offices', 'parent_office_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('offices', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('uq_items_name_category', 'items', type_='unique')
    op.create_index(op.f('ix_items_unit_id'), 'items', ['unit_id'], unique=False)
    op.create_index(op.f('ix_items_category_id'), 'items', ['category_id'], unique=False)
    op.alter_column('items', 'remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('items', 'specification',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('items', 'unit_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('items', 'category_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('items', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_issues_store_date'), 'issues', ['source_store_id', 'issue_date'], unique=False)
    op.create_index(op.f('ix_issues_destination'), 'issues', ['destination_office_id', 'destination_section_id'], unique=False)
    op.alter_column('issues', 'posted_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('issues', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('issues', 'remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('issues', 'destination_section_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('issues', 'destination_office_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('issues', 'source_store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('issues', 'financial_year_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('ix_issue_lines_item'), 'issue_lines', ['item_id'], unique=False)
    op.alter_column('issue_lines', 'remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('issue_lines', 'unit_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('issue_lines', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_inventory_policies_created_by_users'), 'inventory_policies', type_='foreignkey')
    op.drop_constraint(op.f('fk_inventory_policies_updated_by_users'), 'inventory_policies', type_='foreignkey')
    op.create_foreign_key(op.f('fk_inventory_policies_created_by_users'), 'inventory_policies', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_inventory_policies_updated_by_users'), 'inventory_policies', 'users', ['updated_by'], ['id'], ondelete='RESTRICT')
    op.alter_column('inventory_policies', 'updated_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('inventory_policies', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('inventory_policies', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('inventory_policies', 'store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('inventory_policies', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_indents_store_status'), 'indents', ['store_id', 'status'], unique=False)
    op.create_index(op.f('ix_indents_fy_date'), 'indents', ['financial_year_id', 'indent_date'], unique=False)
    op.alter_column('indents', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('indents', 'remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('indents', 'section_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('indents', 'office_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('indents', 'store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('indents', 'financial_year_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('ix_indent_lines_item'), 'indent_lines', ['item_id'], unique=False)
    op.alter_column('indent_lines', 'remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('indent_lines', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('uq_current_financial_year'), 'financial_years', ['is_current'], unique=True, postgresql_where='(is_current = true)')
    op.alter_column('financial_years', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_csr_requesting_store_status'), 'central_store_requisitions', ['requesting_store_id', 'status'], unique=False)
    op.create_index(op.f('ix_csr_fy_date'), 'central_store_requisitions', ['financial_year_id', 'requisition_date'], unique=False)
    op.alter_column('central_store_requisitions', 'closed_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('central_store_requisitions', 'central_approved_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('central_store_requisitions', 'branch_approved_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('central_store_requisitions', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('central_store_requisitions', 'requesting_store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('central_store_requisitions', 'requesting_office_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('central_store_requisitions', 'financial_year_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('ix_csr_lines_item'), 'central_store_requisition_lines', ['item_id'], unique=False)
    op.alter_column('central_store_requisition_lines', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('categories', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('categories', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('uq_assets_serial_no_nonnull'), 'assets', ['serial_no'], unique=True, postgresql_where='(serial_no IS NOT NULL)')
    op.alter_column('assets', 'updated_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('assets', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('assets', 'acquisition_financial_year_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('assets', 'current_section_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('assets', 'current_office_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('assets', 'current_store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('assets', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('asset_movements', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('asset_movements', 'to_section_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('asset_movements', 'to_office_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('asset_movements', 'from_section_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('asset_movements', 'from_office_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('asset_movements', 'to_store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('asset_movements', 'from_store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_constraint('uq_adjustments_verification', 'adjustments', type_='unique')
    op.create_unique_constraint(op.f('uq_adjustments_verification_type'), 'adjustments', ['verification_id', 'adjustment_type'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_adjustments_verification'), 'adjustments', ['verification_id'], unique=False)
    op.create_index(op.f('ix_adjustments_store_status'), 'adjustments', ['store_id', 'status'], unique=False)
    op.alter_column('adjustments', 'posted_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('adjustments', 'authorized_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('adjustments', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('adjustments', 'store_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('adjustments', 'financial_year_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('ix_adjustment_lines_item'), 'adjustment_lines', ['item_id'], unique=False)
    op.alter_column('adjustment_lines', 'unit_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('adjustment_lines', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_index('ix_stock_return_line_assets_asset_id', table_name='stock_return_line_assets')
    op.drop_table('stock_return_line_assets')
    op.drop_index('ix_transfer_line_assets_asset_id', table_name='transfer_line_assets')
    op.drop_table('transfer_line_assets')
    op.drop_index('ix_issue_line_assets_asset_id', table_name='issue_line_assets')
    op.drop_table('issue_line_assets')
    op.drop_table('asset_repairs')
    # ### end Alembic commands ###
