"""Add asset unique constraints

Revision ID: f7f8467a4dae
Revises: c98c94adc301
Create Date: 2026-09-13 11:11:28.778313
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f7f8467a4dae'
down_revision: Union[str, Sequence[str], None] = 'c98c94adc301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_issue_line_assets_issue_line_asset', 'issue_line_assets', ['issue_line_id', 'asset_id'])
    op.create_unique_constraint('uq_stock_return_line_assets_return_line_asset', 'stock_return_line_assets', ['stock_return_line_id', 'asset_id'])
    op.create_unique_constraint('uq_transfer_line_assets_transfer_line_asset', 'transfer_line_assets', ['transfer_line_id', 'asset_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transfer_line_assets_transfer_line_asset', 'transfer_line_assets', type_='unique')
    op.drop_constraint('uq_stock_return_line_assets_return_line_asset', 'stock_return_line_assets', type_='unique')
    op.drop_constraint('uq_issue_line_assets_issue_line_asset', 'issue_line_assets', type_='unique')
    # ### end Alembic commands ###
