"""Central permission catalogue and role matrix for CSMS V2.

The database remains the source of truth at runtime; this module defines the
approved seed configuration in one place so role/action drift is easier to
review and test.
"""

PERMISSIONS = [
    ("STOCK_VIEW", "View stock", "STOCK", "VIEW"),
    ("STOCK_OPENING_CREATE", "Enter and post opening stock", "STOCK", "OPENING_CREATE"),
    ("STOCK_RECEIPT_VIEW", "View receipt documents", "STOCK", "RECEIPT_VIEW"),
    ("STOCK_RECEIPT", "Create/post receipt", "STOCK", "RECEIPT"),
    ("STOCK_ISSUE", "Issue stock", "STOCK", "ISSUE"),
    ("STOCK_TRANSFER_VIEW", "View transfer documents", "STOCK", "TRANSFER_VIEW"),
    ("STOCK_TRANSFER_DISPATCH", "Dispatch transfer", "STOCK", "TRANSFER_DISPATCH"),
    ("STOCK_TRANSFER_RECEIVE", "Receive transfer", "STOCK", "TRANSFER_RECEIVE"),
    ("STOCK_TRANSFER_DISCREPANCY_RESOLVE", "Resolve transfer discrepancy", "STOCK", "TRANSFER_DISCREPANCY_RESOLVE"),
    ("STOCK_RETURN_VIEW", "View return documents", "STOCK", "RETURN_VIEW"),
    ("STOCK_RETURN", "Process stock return", "STOCK", "RETURN"),
    ("STOCK_VERIFY", "Authorize stock verification", "STOCK", "VERIFY"),
    ("STOCK_ADJUST_AUTHORIZE", "Authorize stock adjustment", "STOCK", "ADJUST_AUTHORIZE"),
    ("STOCK_UNSERVICEABLE_AUTHORIZE", "Authorize unserviceable stock", "STOCK", "UNSERVICEABLE_AUTHORIZE"),
    ("STOCK_VERIFICATION_CREATE", "Create stock verification", "STOCK", "VERIFICATION_CREATE"),
    ("STOCK_ADJUST_CREATE", "Create stock adjustment", "STOCK", "ADJUST_CREATE"),
    ("STOCK_ADJUST_POST", "Post stock adjustment", "STOCK", "ADJUST_POST"),
    ("STOCK_UNSERVICEABLE_CREATE", "Report unserviceable stock", "STOCK", "UNSERVICEABLE_CREATE"),
    ("STOCK_UNSERVICEABLE_POST", "Post unserviceable stock", "STOCK", "UNSERVICEABLE_POST"),
    ("INDENT_VIEW", "View indent documents", "INDENT", "VIEW"),
    ("INDENT_CREATE", "Create online indent", "INDENT", "CREATE"),
    ("INDENT_APPROVE", "Approve indent", "INDENT", "APPROVE"),
    ("INDENT_PROCESS", "Record/process physical indent and issue", "INDENT", "PROCESS"),
    ("REQUISITION_VIEW", "View requisition documents", "REQUISITION", "VIEW"),
    ("REQUISITION_CREATE", "Create central store requisition", "REQUISITION", "CREATE"),
    ("REQUISITION_APPROVE_BRANCH", "Approve branch requisition", "REQUISITION", "APPROVE_BRANCH"),
    ("REQUISITION_APPROVE_CENTRAL", "Approve central requisition", "REQUISITION", "APPROVE_CENTRAL"),
    ("ASSET_VIEW", "View assets", "ASSET", "VIEW"),
    ("ASSET_CREATE", "Create asset", "ASSET", "CREATE"),
    ("ASSET_REPAIR", "Send asset for repair", "ASSET", "REPAIR"),
    ("ASSET_REPAIR_RETURN", "Return asset from repair", "ASSET", "REPAIR_RETURN"),
    ("ASSET_UNSERVICEABLE", "Authorize asset as unserviceable", "ASSET", "UNSERVICEABLE"),
    ("ASSET_DISPOSE", "Dispose asset", "ASSET", "DISPOSE"),
    ("ASSET_LOST", "Mark asset as lost", "ASSET", "LOST"),
    ("REGISTER_VIEW", "View operational registers", "REGISTER", "VIEW"),
    ("REPORT_VIEW", "View reports", "REPORT", "VIEW"),
    ("AUDIT_VIEW", "View audit history", "AUDIT", "VIEW"),
    ("PETTY_PURCHASE_VIEW", "View petty purchase documents", "PETTY_PURCHASE", "VIEW"),
    ("PETTY_PURCHASE_CREATE", "Create petty purchase", "PETTY_PURCHASE", "CREATE"),
    ("PETTY_PURCHASE_VERIFY", "Verify petty purchase", "PETTY_PURCHASE", "VERIFY"),
    ("PETTY_PURCHASE_POST", "Post petty purchase", "PETTY_PURCHASE", "POST"),
    ("MASTER_DATA_MANAGE", "Manage master data", "MASTER", "MANAGE"),
    ("ORGANIZATION_MANAGE", "Manage offices, stores and sections", "ORGANIZATION", "MANAGE"),
    ("USER_MANAGE", "Manage users, roles and store assignments", "USER", "MANAGE"),
]

# Approved business roles.  View permissions do not grant transaction rights;
# controller permissions are deliberately separated from storekeeper actions.
ROLE_PERMISSIONS = {
    "SYSTEM_ADMIN": [
        "STOCK_VIEW", "STOCK_RECEIPT_VIEW", "STOCK_TRANSFER_VIEW", "STOCK_RETURN_VIEW",
        "ASSET_VIEW", "REGISTER_VIEW", "REPORT_VIEW", "AUDIT_VIEW", "INDENT_VIEW",
        "REQUISITION_VIEW", "PETTY_PURCHASE_VIEW", "MASTER_DATA_MANAGE", "ORGANIZATION_MANAGE", "USER_MANAGE",
    ],
    "DIRECTOR": [
        "STOCK_VIEW", "STOCK_RECEIPT_VIEW", "STOCK_TRANSFER_VIEW", "STOCK_RETURN_VIEW",
        "ASSET_VIEW", "REGISTER_VIEW", "REPORT_VIEW", "AUDIT_VIEW", "INDENT_VIEW", "REQUISITION_VIEW", "PETTY_PURCHASE_VIEW",
    ],
    "DEPUTY_SUPDT_STORES": [
        "STOCK_VIEW", "STOCK_RECEIPT_VIEW", "STOCK_TRANSFER_VIEW", "STOCK_RETURN_VIEW", "STOCK_VERIFY",
        "STOCK_ADJUST_AUTHORIZE", "STOCK_UNSERVICEABLE_AUTHORIZE", "STOCK_TRANSFER_DISCREPANCY_RESOLVE",
        "REQUISITION_VIEW", "REQUISITION_APPROVE_CENTRAL", "INDENT_VIEW", "INDENT_APPROVE", "REGISTER_VIEW",
        "REPORT_VIEW", "AUDIT_VIEW", "ASSET_VIEW", "PETTY_PURCHASE_VIEW", "PETTY_PURCHASE_VERIFY",
        "ASSET_REPAIR", "ASSET_REPAIR_RETURN", "ASSET_UNSERVICEABLE", "ASSET_DISPOSE", "ASSET_LOST",
    ],
    "GENERAL_STOREKEEPER": [
        "STOCK_VIEW", "STOCK_OPENING_CREATE", "STOCK_RECEIPT_VIEW", "STOCK_RECEIPT", "STOCK_ISSUE",
        "STOCK_TRANSFER_VIEW", "STOCK_TRANSFER_DISPATCH", "STOCK_RETURN_VIEW", "STOCK_RETURN", "INDENT_VIEW", "INDENT_PROCESS",
        "ASSET_VIEW", "ASSET_CREATE", "REGISTER_VIEW", "PETTY_PURCHASE_VIEW", "PETTY_PURCHASE_CREATE", "PETTY_PURCHASE_POST",
        "ASSET_REPAIR", "ASSET_REPAIR_RETURN", "STOCK_VERIFICATION_CREATE", "STOCK_ADJUST_CREATE", "STOCK_ADJUST_POST",
        "STOCK_UNSERVICEABLE_CREATE", "STOCK_UNSERVICEABLE_POST",
    ],
    "ASSISTANT_STOREKEEPER": [
        "STOCK_VIEW", "STOCK_OPENING_CREATE", "STOCK_RECEIPT_VIEW", "STOCK_RECEIPT", "STOCK_ISSUE",
        "STOCK_TRANSFER_VIEW", "STOCK_TRANSFER_DISPATCH", "STOCK_RETURN_VIEW", "STOCK_RETURN", "INDENT_VIEW", "INDENT_PROCESS",
        "ASSET_VIEW", "ASSET_CREATE", "REGISTER_VIEW", "PETTY_PURCHASE_VIEW", "PETTY_PURCHASE_CREATE", "PETTY_PURCHASE_POST",
        "ASSET_REPAIR", "ASSET_REPAIR_RETURN", "STOCK_VERIFICATION_CREATE", "STOCK_ADJUST_CREATE", "STOCK_ADJUST_POST",
        "STOCK_UNSERVICEABLE_CREATE", "STOCK_UNSERVICEABLE_POST",
    ],
    "BRANCH_HEAD": [
        "STOCK_VIEW", "STOCK_RECEIPT_VIEW", "STOCK_TRANSFER_VIEW", "STOCK_RETURN_VIEW", "INDENT_VIEW", "INDENT_APPROVE",
        "REQUISITION_VIEW", "REQUISITION_APPROVE_BRANCH", "REGISTER_VIEW", "REPORT_VIEW", "ASSET_VIEW",
        "PETTY_PURCHASE_VIEW", "PETTY_PURCHASE_VERIFY", "STOCK_VERIFY", "STOCK_ADJUST_AUTHORIZE", "STOCK_UNSERVICEABLE_AUTHORIZE",
        "STOCK_TRANSFER_DISCREPANCY_RESOLVE", "ASSET_UNSERVICEABLE", "ASSET_DISPOSE", "ASSET_LOST",
    ],
    "BRANCH_STOREKEEPER": [
        "STOCK_VIEW", "STOCK_OPENING_CREATE", "STOCK_RECEIPT_VIEW", "STOCK_RECEIPT", "STOCK_ISSUE",
        "STOCK_TRANSFER_VIEW", "STOCK_TRANSFER_RECEIVE", "STOCK_RETURN_VIEW", "STOCK_RETURN", "INDENT_VIEW", "INDENT_PROCESS", "INDENT_CREATE",
        "REQUISITION_VIEW", "REQUISITION_CREATE", "ASSET_VIEW", "ASSET_CREATE", "REGISTER_VIEW", "PETTY_PURCHASE_VIEW",
        "PETTY_PURCHASE_CREATE", "PETTY_PURCHASE_POST", "ASSET_REPAIR", "ASSET_REPAIR_RETURN", "STOCK_VERIFICATION_CREATE",
        "STOCK_ADJUST_CREATE", "STOCK_ADJUST_POST", "STOCK_UNSERVICEABLE_CREATE", "STOCK_UNSERVICEABLE_POST",
    ],
    "SECTION_USER": ["INDENT_VIEW", "INDENT_CREATE"],
}

ROLE_CODES = tuple(ROLE_PERMISSIONS)
PERMISSION_CODES = {row[0] for row in PERMISSIONS}
